version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: test-post-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: test_post_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d test_post_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
