export const SERVICE_PREFIX = 'QS';

export const ENTITY_PREFIXES = {
  QUESTION: 'QST',
  CATEGORY: 'CAT',
  AUDIO: 'AUDIO',
  EXAM: 'EXAM',
  IMAGE: 'IMG',
  RESOURCE: 'RES',
};

export const USECASE_INPUT_PREFIXES = {
  CREATE_CATEGORY: 'CAT:CREATE',
  UPDATE_CATEGORY: 'CAT:UPDATE',
  DELETE_CATEGORY: 'CAT:DELETE',
  LIST_CATEGORIES: 'CAT:LIST',
};
